language: cpp
matrix:
  include:
  - os: linux
    compiler: clang
    name: clang-ninja
    sudo: required
    env: TASK=clang
    dist: xenial
    cache:
      ccache: true
    addons:
      apt:
        sources:
        - sourceline: ppa:ubuntu-toolchain-r/test
        packages:
        - ninja-build
    script:
    - bash travis.sh
    deploy:
    #- provider: releases
      #api_key: "$GITHUB_TOKEN"
      #overwrite: true
      #file: CryptoCore-linux-master.tgz
      #skip_cleanup: true
      #tag_name: master
      #on:
        #tags: false
        #branch: master
        #repo: Cryptonite-UO/CryptoCore
    #- provider: releases
      #api_key: "$GITHUB_TOKEN"
      #overwrite: true
      #file: CryptoCore-linux-v$TRAVIS_TAG.tgz
      #skip_cleanup: true
      #on:
        #tags: true
        #repo: Cryptonite-UO/CryptoCore
    install:
    - |
      CMAKE_URL="https://cmake.org/files/v3.13/cmake-3.13.5-Linux-x86_64.tar.gz"
      mkdir cmake && travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
      export PATH=${PWD}/cmake/bin:${PATH}
    - cmake --version
  - os: osx
    sudo: false
    addons:
      homebrew:
        packages:
        - ccache
        - ninja
    install:
    - export PATH="/usr/local/opt/ccache/libexec:$PATH"
    osx_image: xcode10
    cache:
      ccache: true
    script:
    - bash travis.sh
    #deploy:
    #- provider: releases
      #api_key: "$GITHUB_TOKEN"
      #overwrite: true
      #file: "sphereX64-osx.zip"
      #skip_cleanup: true
      #tag_name: master
      #on:
        #tags: false
        #branch: master
        #repo: Cryptonite-UO/CryptoCore
    #- provider: releases
      #api_key: "$GITHUB_TOKEN"
      #overwrite: true
      #file: "sphereX64-osx.zip"
      #skip_cleanup: true
      #on:
        #tags: true
        #repo: Cryptonite-UO/CryptoCore
  - os: windows
    cache:
      ccache: true
    script:
    - bash travis.sh
    #before_deploy:
        #- git tag -f master; sleep 5
    #deploy:
    #- provider: releases
     # api_key: "$GITHUB_TOKEN"
      #overwrite: true
      #file: "sphereX64-windows.zip"
      #skip_cleanup: true
      #tag_name: master
      #on:
        #tags: false
        #branch: master
        #repo: Cryptonite-UO/CryptoCore
    #- provider: releases
      #api_key: "$GITHUB_TOKEN"
      #overwrite: true
      #file: "sphereX64-windows.zip"
      #skip_cleanup: true
      #on:
        #tags: true
        #repo: Cryptonite-UO/CryptoCore
